services:

  mysql:
    image: mysql:8.0
    container_name: stayease-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Root123
      MYSQL_DATABASE: stayEase_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/stayease_backup.sql:/docker-entrypoint-initdb.d/stayease_backup.sql:ro

  backend:
    image: stayease-backend:latest
    container_name: stayease-backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stayEase_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root123
    ports:
      - "8080:8080"

  frontend:
    image: stayease-frontend:latest
    container_name: stayease-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data: